### ISSUE TITLE
stuff, lol

### ISSUE THREAD

**Issue by sparklyballs** [linuxserver/docker-snipe-it#1]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

stuff i've seen so far
+ stylistic changes (tabs, spaces etc) 
+ don't make folders or links etc to /config in the Dockerfile
+ the loop for making the folders in the init file would be better served with 
mkdir -p /blah/{folder1,folder2,folder2} etc.........
+ symlinks are the bastard son of a pestilent donkey, linking internal to volume mounts, if you must use them i can't see why you wouldn't just link the storage folder to the volume mount with one of the evil things, rather than multiple symlinks like that.
+ need to give docker and core group admin status to the repo

**Comment by thelamer** [comment]
We cannot get around symlinks unless we pull to mounted storage, which gets us into an upgrade and versioning number nightmare. 

They currently have a docker build process and use storage for external stuff to the core app. https://github.com/snipe/snipe-it/blob/master/Dockerfile , so we should be pretty hands off using your approach of doing what you suggested and doing the whole folder. It sucks the app has no logic for folder generation, but there will likely be some maintenance down the line when they add directories. 

I agree on all other points for cleanup and over coding the folder/symlink generation will get started tomorrow and ping when completed.

**Comment by aptalca** [comment]
I noticed that you're sed'ing a bunch of variables in php.ini

Instead, you can put a custom ini under /etc/php7/conf.d and whatever values you put in there will append and supersede the main php.ini

In the nginx baseimage, we use that trick to allow user customization of php.ini: https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/cont-init.d/20-config#L18

**Comment by thelamer** [comment]
All feedback processed closing issue
