### ISSUE TITLE
500 Server Error on "Create Database Tables" Step of Setup

### ISSUE THREAD

**Issue by PartTimeJS** [linuxserver/docker-snipe-it#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior

On step 2 of the Setup, the web page throws `500 | Server Error.` 
Back on Step 1, it says connection to the db was good.
This issue was replicated by Spad in the discord. 

## Steps to Reproduce

1. Create docker-compose.yml from example in the docs
2. docker-compose up -d
3. Go to the ip:port which forwards to setup prompt
4. Click "Next: Create Database Tables"

## Environment
**OS:** Ubuntu 20.04 virtualized in Hyper-V
**CPU architecture:** x86_64
**How docker service was installed:** apt

## Command used to create docker container (run/create/compose/screenshot)

docker-compose up -d

```version: "3"
services:
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=-------------------
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=-----------------------
      - MYSQL_DATABASE=snipeit
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./config:/config
    environment:
      - APP_URL=----------------------------
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=-------------------
      - PGID=1000
      - PUID=1000
    ports:
      - "8082:443"
      - "8080:80"
```

## Docker logs

There are no docker logs or errors when this behavior happens.

**Comment by Tdarnell** [comment]
+1 also having this issue

**Comment by thelamer** [comment]
Can you use the new compose example referencing our container and let me know the results. I cannot duplicate this.

**Comment by thelamer** [comment]
I have tested thoroughly this happens when it cannot connect to the database. On a clean setup using the new compose example though I cannot duplicate. Closing issue.
