### ISSUE TITLE
Using docker compose example entry on arm64 fails on database container creation

### ISSUE THREAD

**Issue by f-steff** [linuxserver/docker-snipe-it#18]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When installing this (these) image(s) on ubuntu/arm64 using the docker-compose example from https://hub.docker.com/r/linuxserver/snipe-it the following error occur:

```
Pulling MySQL (MySQL:5)...
5: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
```

I found replacing `image: mysql:5` in the docker compose file with `linuxserver/mariadb` fixes the problem.

------------------------------

## Expected Behavior

Database should be installed correctly, and the entire installation should run.

## Current Behavior

An error occurs.

## Environment
**OS:** ubuntu 20.10
**CPU architecture:** arm64

**Comment by tobbenb** [comment]
Looks like the MySQL  container is amd64 only.

**Comment by TheSpad** [comment]
I think the example was written pre-mariadb support so we might just be able to switch it out?

**Comment by axilleas** [comment]
MariaDB is still missing the armv7 arch. I got it working with https://github.com/beercan1989/docker-arm-mysql.
