### ISSUE TITLE
Hardcoded "localhost" a href source in qr- / barcodes

### ISSUE THREAD

**Issue by hennibadger16** [linuxserver/docker-snipe-it#25]
Hi,

I'm on the latest release as of now which would be  Version v5.1.8 - build 6148 (master) and unfortunately I'm encountering errors with the rendering of certain images - especially asset qr-codes:

![image](https://user-images.githubusercontent.com/8727638/127463523-615c00b6-41ca-45dd-964d-2070419f6bab.png)

It seems to me that there are hardcoded references to localhost any many URLs. 

Would that be fixable? Anything I can do about it?

Tahnk you very much!

**Comment by techwithjake** [comment]
@hennibadger16 Try adding the environment label 
`APP_URL=https://your.fqdn`
To your compose file. After doing so, QR codes starting populating properly for me.
