### ISSUE TITLE
Add scheduler crontab entry into the docker image

### ISSUE THREAD

**Issue by imifarago** [linuxserver/docker-snipe-it#31]
## Desired Behavior
Add artisan scheduler crontab entry into /etc/crontabs 
Altering: https://snipe-it.readme.io/docs/configuring-alerts-backups

/etc/crontabs/snipeit should contain:
`* * * * * abc /usr/bin/php /var/www/html/artisan schedule:run >> /dev/null 2>&1`

Add these also - or the backup conditionally:
/path/to/php artisan snipeit:backup
/path/to/php artisan backup:clean
/path/to/php artisan snipeit:expiring-alerts
/path/to/php artisan snipeit:inventory-alerts
/path/to/php artisan snipeit:expected-checkin
/path/to/php artisan snipeit:user-inventory
/path/to/php artisan snipeit:upcoming-audits

## Current Behavior
Now crontab file have to be mounted if you want to alerting, but it should be default on laravel based applications.

**Comment by jchue** [comment]
I believe you can use the [cron mod](https://github.com/linuxserver/docker-mods/tree/universal-cron).

**Comment by nemchik** [comment]
https://github.com/linuxserver/docker-snipe-it/pull/49 will include the scheduler in the image. `lspipepr/snipe-it:v6.0.14-pkg-d5309d55-pr-49` needs testing. Please reply on #49 if you're able to confirm this works as needed.
