### ISSUE TITLE
not work env setting 'NGINX_APP_URL', 'APP_TIMEZONE', APP_LOCALE'

### ISSUE THREAD

**Issue by directe02** [linuxserver/docker-snipe-it#35]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

work env setting 'NGINX_APP_URL', 'APP_TIMEZONE', APP_LOCALE'

## Current Behavior

not work env setting 'NGINX_APP_URL', 'APP_TIMEZONE', APP_LOCALE'
(ex) all link connect localhost
## Steps to Reproduce

1. (in container) vi /var/www/html/.env
2. #APP_URL=127.0.0.1 -> APP_URL=${NGINX_APP_URL}
3. #APP_TIMEZONE=US/Pacific -> APP_TIMEZONE=${APP_TIMEZONE}
4. #APP_LOCALE=en -> APP_LOCALE=${APP_LOCALE}

## Environment
**OS:** centos 8 stream
**CPU architecture:** x86_64
**How docker service was installed:**

test information (kubernetes)
Image: linuxserver/snipe-it:latest
Image ID: docker-pullable://linuxserver/snipe-it@sha256:8d2d2f0afca8573997ed777f897127dad49e66f2b8bf046b2a6ef8f37c09012b
Port: 80/TCP
Host Port: 0/TCP
State: Running
Started: Wed, 23 Feb 2022 12:23:27 +0900

**Comment by abel408** [comment]
I am also seeing this issue.
Using APP_URL instead of NGINX_APP_URL in the docker-compoe.yml file seems to solve it, but I'm not sure if that has any unwanted side affects.

I'm also getting Database connection issues so I'm not sure if the env variables for the mysql connection are working either.
