### ISSUE TITLE
Outlook Email Server 501 invalid domain

### ISSUE THREAD

**Issue by jayket** [linuxserver/docker-snipe-it#44]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Email should sent without issue and return 250 code to complete email process

## Current Behavior
Email server is returning error code 501 with message "501 5.5.4 Invalid domain name [BL1PR13CA0360.namprd13.prod.outlook.com]
 

## Steps to Reproduce

1. use any outlook email for the default settings
2.
3.
4.

## Environment
**OS:*Raspbian v11 lite*
**CPU architecture:arm32
**How docker service was installed:**
from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
version: "3"
services:
  mysql:
    image: linuxserver/mariadb
    container_name: Snipe_mysql
    restart: unless-stopped
    volumes:
      - /homw/admin/appdata/snipeit/mysql:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=snipe
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: Snipe_it
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - /home/admin/appdata/snipeit:/config
    environment:
      - APP_DEBUG=true
      - APP_TIMEZONE=America/New_York
      - APP_URL=
      - NGINX_APP_URL=
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - PGID=1000
      - PUID=1000
# Email settings
      - MAIL_DRIVER=smtp
      - MAIL_PORT_587_TCP_ADDR=smtp-mail.outlook.com
      - MAIL_PORT_587_TCP_PORT=587
      - MAIL_ENV_USERNAME=example@outlook.com
      - MAIL_ENV_PASSWORD=example
      - MAIL_ENV_ENCRYPTION=TLS
      - MAIL_ENV_FROM_ADDR=example@outlook.com
      - MAIL_ENV_FROM_NAME=Snipe-IT

    ports:
      - "3001:80"

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
Snipe-IT: https://snipeitapp.com/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-config: executing... 
[cont-init.d] 40-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

App run in debug:
Expected response code 250 but got code "501", with message "501 5.5.4 Invalid domain name [BL1PR13CA0360.namprd13.prod.outlook.com]
 "
/var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php#459

**Comment by drizuid** [comment]
This looks like an upstream issue and should be taken up with the devs of snipe-it. We support the container, not the application within.
