### ISSUE TITLE
running docker-compose up -d on Raspberry Pi(Armhf) is resulting in an error

### ISSUE THREAD

**Issue by rajasiman** [linuxserver/docker-snipe-it#9]
Hello there,

I am trying to install snipe-it on a Raspberry Pi 2B+. The architecture is armhf. I used the provided docker-compose template and set up the passwords and volumes correctly:
<pre>version: &quot;3&quot;
services:
  mysql:
    image: mysql:5
    container_name: snipe_mysql
    restart: always
    volumes:
      - ./snipe-it_mysql_config:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=******************
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=******************
      - MYSQL_DATABASE=snipe
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./snipe-it_config:/config
    environment:
      - APP_URL=192.168.1.100:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=******************
      - PGID=1000
      - PUID=1000
    ports:
      - &quot;8080:80&quot;
</pre>

On running the 'docker-compose up -d' command to start the container, the following is the output.

<pre>Pulling mysql (mysql:5)...
5: Pulling from library/mysql
<font color="#CC0000">ERROR</font>: no matching manifest for unknown in the manifest list entries
</pre>

I then looked at your repositories and saw there was no mysql image, so i changed the docker-compose.yml to the following and the installation actually went through. The application did not start though, I got a 'Something went wrong' message.

Modified docker-compose.yml:
<pre>version: &quot;3&quot;
services:
  mariadb:
    image: linuxserver/mariadb
    container_name: snipe_mariadb
    restart: always
    volumes:
      - ./mariadb_config:/var/lib/mysql
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=******************
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=******************
      - MYSQL_DATABASE=snipe
    ports:
      - 3306:3306
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./snipe-it_config:/config
    environment:
      - APP_URL=192.168.1.100:8080
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=******************
      - PGID=1000
      - PUID=1000
    ports:
      - &quot;8080:80&quot;
</pre>

Host OS: Raspbian Stretch Lite, released on 2019-04-08
Command: <code>docker-compose up -d</code>

Thank you for your time!

**Comment by j0nnymoe** [comment]
You haven't updated the mariadb with the correct variables from our readme: https://github.com/linuxserver/docker-mariadb/blob/master/README.md

**Comment by thelamer** [comment]
Snipe-it is not compatible with mysql or mariadb 10.x so our image will not work. 
You will need to find a Mysql image in the 5.x series that is compatible with your hardware. We have done our part, but we cannot guarantee compatibility with something like this outside of our control.

**Comment by rajasiman** [comment]
### !!Solved!!

@thelamer @j0nnymoe for your information. I got this to work with the linuxserver images alone! I am attaching the reference <code>docker-compose.yml</code> here in case you would want to update the sample given in the README. In case it is not helpful, I will leave this here for someone who's looking to do the same sometime down the line!

thanks a bunch for all the work in maintaining the images! 

docker-compose.yml
<pre>version: "3"
services:
  snipeit:
    image: linuxserver/snipe-it:latest
    container_name: snipe-it
    restart: always
    volumes:
      - < path to snipe-it data >:/config
    environment:
      - APP_URL=< your application URL IE 192.168.10.1:8080>
      - MYSQL_PORT_3306_TCP_ADDR=mariadb
      - MYSQL_PORT_3306_TCP_PORT=3306
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=< secret user password >
      - PGID=1000
      - PUID=1000
    ports:
      - &quot;8080:80&quot;
    depends_on:
      - mariadb
  mariadb:
    image: linuxserver/mariadb
    container_name: snipe_mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MYSQL_ROOT_PASSWORD=< secret user password >
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=< secret user password >
      - MYSQL_DATABASE=snipe
    volumes:
      - < path to mariadb data >:/config
    ports:
      - 3306:3306
    restart: unless-stopped</pre>

**Comment by ClassyWombat** [comment]
For anyone using Portainer-CE instead of Docker-Compose and this isn't working on pi: Check if the network is the default bridge network. If it is you need to manually specify a network using the "network_mode" variable.
